name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust based on your project's Node.js version

      - name: Install dependencies
        run: npm install  # Use npm or yarn based on your project

      - name: Build Tailwind CSS
        run: npx tailwindcss -i ./public/styles/index.css -o ./public/styles/main.css --minify

      - name: Copy index.html to root
        run: cp public/index.html .  # Ensure you have the correct path to your index.html

      - name: Deploy to GitHub Pages
        uses: actions/github-pages@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public 
