name: Deploy to GitHub Pages and Firebase

on:
  push:
    branches:
      - main  # Change this to your main branch if different

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust based on your project's Node.js version

      - name: Install dependencies
        run: npm install  # Use npm or yarn based on your project

      - name: Build Tailwind CSS
        run: npx tailwindcss -i ./public/styles/index.css -o ./public/styles/main.css --minify

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public  # Adjust to the correct path where your built files are located

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MY_FIREBASE_JS_APP }}
        run: |
          firebase deploy --token $FIREBASE_TOKEN
